config/routes.rb
Rails.application.routes.draw do

  resources :contracts, only: [:index, :show, :new], path: "contratos"
  resources :finances, only: [:index], path: "financeiro"
  resources :reports, only: [:index], path: "relatorios"
  resources :users, only: [:index], path: "usuarios"

  devise_for :users
  get 'pages/home'
  get '/dashboard', to: "pages#dashboard"
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
	belongs_to :user
end

app/models/finance.rb
class Finance < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :contracts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :resource_name, :resource, :devise_mapping, :resource_class
  before_action :authenticate_user!

  # before_action :configure_permitted_parameters, if: :devise_controller?

  # def configure_permitted_parameters
  #   # For additional fields in app/views/devise/registrations/new.html.erb
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  #   # For additional in app/views/devise/registrations/edit.html.erb
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  # end
  
  private

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def after_sign_in_path_for(resource)
    dashboard_path
  end

  private

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end


end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
	def index
		if params[:query].present?
	      @contracts = Contract.joins(:user).where("email ILIKE ?", "%#{params[:query]}%")
	    else
	      @contracts = Contract.all
	    end
	end

	def new
		@contract = Contract.new
	end

	def show
		@contract = Contract.find(params[:id])
	end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
	def index
		@finances = Finance.all
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end

  def dashboard
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	def index
		@reports = Report.all
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contracts/index.html.erb
<nav>
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 py-3 px-4 text-center bg-white">
				<p class="mb-0 aud-text-color"><strong>CONTRATOS</strong></p>
			</div>
		</div>
	</div>
</nav>
<section>
	<div class="container mt-5 border-line bg-white p-5">
		<div class="row d-flex justify-content-center align-items-center">
			<div class="col-sm-6 px-5">
				<div class="form-check form-check-inline">
				  <input class="form-check-input" type="checkbox" name="inlineRadioOptions" id="inlineRadio1" value="option1">
				  <label class="form-check-label" for="inlineRadio1">Data</label>
				</div>
				<div class="form-check form-check-inline">
				  <input class="form-check-input" type="checkbox" name="inlineRadioOptions" id="inlineRadio1" value="option1">
				  <label class="form-check-label" for="inlineRadio1">Nome</label>
				</div>
				<div class="form-check form-check-inline">
				  <input class="form-check-input" type="checkbox" name="inlineRadioOptions" id="inlineRadio1" value="option1">
				  <label class="form-check-label" for="inlineRadio1">Area</label>
				</div>
				<%= form_tag contracts_path, method: :get do %>
				  <%= text_field_tag :query,
				    params[:query],
				    class: "form-control",
				    placeholder: "Pesquisar Contratos"
				  %>
				  <%= submit_tag "Pesquisar", class: "btn btn-outline-primary mt-2 search-btn" %>
				<% end %>	
				<div class="box rounded mt-2 p-2">
					<ul class="list-inline">
						<% @contracts.each do |contract| %>
							<li><%= link_to contract.user.email, contract_path(contract) %></li>
						<% end %>
					</ul>
				</div>
			</div>
			<div class="col-sm-6 mt-sm-0 mt-3">
				<%= image_tag "logo.png", :width => "300", class: "img-fluid d-flex mx-auto" %>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="container mt-5">
		<div class="row">
			<div class="col-sm-6 offset-sm-3 text-center">
				<%= link_to "GERAR NOVO CONTRATO", new_contract_path, class: "btn border-line py-4 px-5 aud-text-color bg-white" %>		
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<%= link_to dashboard_path do %>
					<i class="fas fa-arrow-circle-left fa-2x aud-text-color"></i>
				<% end %>
			</div>
		</div>
	</div>
</section>

app/views/contracts/new.html.erb
<nav>
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 py-3 px-4 text-center bg-white">
				<p class="mb-0 aud-text-color"><strong>NOVO CONTRATO</strong></p>
			</div>
		</div>
	</div>
</nav>
<section>
	<div class="container">
		<div class="row">
			<div class="col-sm-6 offset-sm-3 bg-white mt-5 p-4 rounded">
				<form>
					<div class="form-row">
					  <div class="form-group col-sm-6">
					    <label for="exampleInputEmail1">Propriedade</label>
					    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="000607">
					    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
					  </div>
					  <div class="form-group col-sm-6">
					    <label for="exampleInputEmail1">Proprietário</label>
					    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="AC AGROPECUARIA" disabled>
					    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
					  </div>
					  <div class="form-group col-sm-12">
						<div class="form-check">
						  <input type="checkbox" class="form-check-input" id="exampleCheck1">
					      <label class="form-check-label" for="exampleCheck1">maior 25</label>
					    </div>
					  </div>
					</div>
					<div class="form-row">
					  <div class="form-group col-sm-12">
					    <label for="exampleInputPassword1">Usuário</label>
					    <select class="form-control" id="exampleFormControlSelect1">
					      <option value="" disabled selected>Selecione o usuário</option>
					      <option>César Morom</option>
					      <option>Júlio Backer</option>
					      <option>Aline Moraes</option>
					      <option>Cristina Souza</option>
					      <option>....</option>
					    </select>
					  </div>
					</div>
					<div class="form-row">
					  <div class="form-group col-sm-4">
					    <label for="exampleInputPassword1">Area Natural</label>
					    <input type="number" class="form-control" id="exampleInputPassword1" placeholder="120">
					  </div>
					  <div class="form-group col-sm-4">
					    <label for="exampleInputPassword1">Area Bombada</label>
					    <input type="number" class="form-control" id="exampleInputPassword1" placeholder="25">
					  </div>
					  <div class="form-group col-sm-4">
					    <label for="exampleInputPassword1">Area Total</label>
					    <input type="number" class="form-control" id="exampleInputPassword1" placeholder="145" disabled>
					  </div>
					</div>
					<%= link_to contracts_path, class: "mt-2 btn btn-primary text-white" do %>
				  		<i class="fas fa-file-signature"></i> Emitir Contrato
					<% end %>
				</form>
			</div>	
		</div>
		<%= link_to contracts_path do %>
			<i class="fas fa-arrow-circle-left fa-2x aud-text-color"></i>
		<% end %>
	</div>
</section>

app/views/finances/index.html.erb
<%= @finances %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="theme-color" content="#3F4393">
    <title>Sistema AUD</title>
    <%= favicon_link_tag 'logo.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<nav>
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 py-3 px-4 d-flex justify-content-between align-items-center bg-white">
				<p class="mb-0 aud-text-color"><strong>PAINEL DE CONTROLE</strong></p>
				<%= image_tag "logo.png", class: "logo" %>
			</div>
		</div>
	</div>
</nav>
<section>
	<div class="container dashboard_height d-flex align-items-center justify-content-center">
		<div class="row border-line bg-white">
			<div class="col-sm-12">
				<div class="row py-5 px-5">
					<div class="col-sm-3">
						<%= link_to users_path do %>
							<div class="border-line-2 d-flex justify-content-center align-items-center p-5 bg-white my-sm-0 my-2">
								<i class="fas fa-users"></i>
								<p class="ml-2">Usuários</p>
							</div>
						<% end %>
					</div>
					<div class="col-sm-3">
						<%= link_to contracts_path do %>
							<div class="border-line-2 d-flex justify-content-center align-items-center p-5 bg-white my-sm-0 my-2">
								<i class="fas fa-file-signature"></i>
								<p class="ml-2">Contratos</p>
							</div>
						<% end %>
					</div>
					<div class="col-sm-3">
						<%= link_to reports_path do %>
							<div class="border-line-2 d-flex justify-content-center align-items-center p-5 bg-white my-sm-0 my-2">
								<i class="fas fa-chart-line"></i>
								<p class="ml-2">Relatórios</p>
							</div>
						<% end %>
					</div>
					<div class="col-sm-3">
						<%= link_to finances_path do %>
							<div class="border-line-2 d-flex justify-content-center align-items-center p-5 bg-white my-sm-0 my-2">
								<i class="fas fa-file-invoice-dollar"></i>
								<p class="ml-2">Finanças</p>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/pages/home.html.erb
<header class="bg-white">	
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 height-100-vh d-flex justify-content-center align-items-center">
				<div>
					<%= image_tag "logo.png", :width => "500", class: "mb-5 img-fluid" %>
					<% if !user_signed_in? %>
						<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
						  <div class="form-inputs">
						    <%= f.input :email, label: false, placeholder: "usuário", autofocus: true%>
						    <%= f.input :password, label: false, placeholder: "senha" %>
						  </div>
						  <div class="form-actions text-right">
						    <%= f.button :submit, "ENTRAR", class: "btn aud-bg-color text-white" %>
						  </div>
						<% end %>
					<% else %>
      					<%= link_to "Sair", destroy_user_session_path, class: 'btn btn-danger btn-block', method: :delete %>
          			<% end %>
				</div>
			</div>
		</div>
	</div>
</header>

app/views/reports/index.html.erb
<%= @reports %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>